import React from 'react'

export default function RankChart() {
    return (
        <div>
        <div className="pr-chart-title">Power Ranks</div>
        <div id="chart-container" className="chart-table">
            <div className="cCover">
              <div className="col1">
                  <div className="chTitles">XO</div>
                  <div className="chSymbols xo">*</div>
                  <div className="chNumbers">Rank</div>
                  <div className="rH">01</div>
                  <div className="rH">02 03</div>
                  <div className="rH">04 06</div>
                  <div className="rH">07 10</div>
                  <div className="rH">11 15</div>
                  <div className="rH">16 20</div>
                  <div className="rH">21 25</div>
                  <div className="rH">26 30</div>
                  <div className="rH">31 35</div>
                  <div className="rH">36 40</div>
                  <div className="rH">41 45</div>
                  <div className="rH">46 50</div>
                  <div className="rH">51 55</div>
                  <div className="rH">56 60</div>
                  <div className="rH">61 65</div>
                  <div className="rH">66 70</div>
                  <div className="rH">71 75</div>
                  <div className="rH">76 80</div>
                  <div className="rH">81 85</div>
                  <div className="rH">86 90</div>
                  <div className="rH">91 94</div>
                  <div className="rH">95 97</div>
                  <div className="rH">98 99</div>
                  <div className="rH">100</div>
              </div>
              <div className="col2">
                  <div className="chTitles">Decrepit</div>
                  <div className="chSymbols">De</div>
                  <div className="chNumbers">0</div>
                  <div className="c2c">01</div>
                  <div className="c2c">02 03</div>
                  <div className="c2c">04 06</div>
                  <div className="c2c">07 10</div>
                  <div className="c2c">11 15</div>
                  <div className="c2c">16 20</div>
                  <div className="c2c">21 25</div>
                  <div className="c2c">26 30</div>
                  <div className="c2c">31 35</div>
                  <div className="c2c">36 40</div>
                  <div className="c2c">41 45</div>
                  <div className="c2c">46 50</div>
                  <div className="c2c">51 55</div>
                  <div className="c2c cg80">56 60</div>
                  <div className="c2c cg70">61 65</div>
                  <div className="c2c cg60">66 70</div>
                  <div className="c2c cg50">71 75</div>
                  <div className="c2c cg40">76 80</div>
                  <div className="c2c cg30">81 85</div>
                  <div className="c2c cg">86 90</div>
                  <div className="c2c cg">91 94</div>
                  <div className="c2c cy">95 97</div>
                  <div className="c2c cy">98 99</div>
                  <div className="c2c cr">100</div>
              </div>
              <div className="col3">
                  <div className="chTitles">Feeble</div>
                  <div className="chSymbols">Fe</div>
                  <div className="chNumbers">1</div>
                  <div className="c3c">01</div>
                  <div className="c3c">02 03</div>
                  <div className="c3c">04 06</div>
                  <div className="c3c">07 10</div>
                  <div className="c3c">11 15</div>
                  <div className="c3c">16 20</div>
                  <div className="c3c">21 25</div>
                  <div className="c3c">26 30</div>
                  <div className="c3c">31 35</div>
                  <div className="c3c">36 40</div>
                  <div className="c3c">41 45</div>
                  <div className="c3c">46 50</div>
                  <div className="c3c cg80">51 55</div>
                  <div className="c3c cg70">56 60</div>
                  <div className="c3c cg60">61 65</div>
                  <div className="c3c cg50">66 70</div>
                  <div className="c3c cg40">71 75</div>
                  <div className="c3c cg30">76 80</div>
                  <div className="c3c cg">81 85</div>
                  <div className="c3c cg">86 90</div>
                  <div className="c3c cy30">91 94</div>
                  <div className="c3c cy">95 97</div>
                  <div className="c3c cy">98 99</div>
                  <div className="c3c cr">100</div>
              </div>
              <div className="col4">
                  <div className="chTitles">Poor</div>
                  <div className="chSymbols">Pr</div>
                  <div className="chNumbers">2</div>
                  <div className="c4c">01</div>
                  <div className="c4c">02 03</div>
                  <div className="c4c">04 06</div>
                  <div className="c4c">07 10</div>
                  <div className="c4c">11 15</div>
                  <div className="c4c">16 20</div>
                  <div className="c4c">21 25</div>
                  <div className="c4c">26 30</div>
                  <div className="c4c">31 35</div>
                  <div className="c4c">36 40</div>
                  <div className="c4c">41 45</div>
                  <div className="c4c cg80">46 50</div>
                  <div className="c4c cg70">51 55</div>
                  <div className="c4c cg60">56 60</div>
                  <div className="c4c cg50">61 65</div>
                  <div className="c4c cg40">66 70</div>
                  <div className="c4c cg30">71 75</div>
                  <div className="c4c cg">76 80</div>
                  <div className="c4c cg">81 85</div>
                  <div className="c4c cy30">86 90</div>
                  <div className="c4c cy30">91 94</div>
                  <div className="c4c cy">95 97</div>
                  <div className="c4c cy">98 99</div>
                  <div className="c4c cr">100</div>
              </div> 
              <div className="col5">
                  <div className="chTitles">Typical</div>
                  <div className="chSymbols">Ty</div>
                  <div className="chNumbers">3</div>
                  <div className="c5c">01</div>
                  <div className="c5c">02 03</div>
                  <div className="c5c">04 06</div>
                  <div className="c5c">07 10</div>
                  <div className="c5c">11 15</div>
                  <div className="c5c">16 20</div>
                  <div className="c5c">21 25</div>
                  <div className="c5c">26 30</div>
                  <div className="c5c">31 35</div>
                  <div className="c5c">36 40</div>
                  <div className="c5c cg80">41 45</div>
                  <div className="c5c cg70">46 50</div>
                  <div className="c5c cg60">51 55</div>
                  <div className="c5c cg50">56 60</div>
                  <div className="c5c cg40">61 65</div>
                  <div className="c5c cg30">66 70</div>
                  <div className="c5c cg">71 75</div>
                  <div className="c5c cg">76 80</div>
                  <div className="c5c cy30">81 85</div>
                  <div className="c5c cy30">86 90</div>
                  <div className="c5c cy">91 94</div>
                  <div className="c5c cy">95 97</div>
                  <div className="c5c cr">98 99</div>
                  <div className="c5c cr">100</div>
              </div>
              <div className="col6">
                  <div className="chTitles">Good</div>
                  <div className="chSymbols">Gd</div>
                  <div className="chNumbers">4</div>
                  <div className="c6c">01</div>
                  <div className="c6c">02 03</div>
                  <div className="c6c">04 06</div>
                  <div className="c6c">07 10</div>
                  <div className="c6c">11 15</div>
                  <div className="c6c">16 20</div>
                  <div className="c6c">21 25</div>
                  <div className="c6c">26 30</div>
                  <div className="c6c">31 35</div>
                  <div className="c6c cg80">36 40</div>
                  <div className="c6c cg70">41 45</div>
                  <div className="c6c cg60">46 50</div>
                  <div className="c6c cg50">51 55</div>
                  <div className="c6c cg40">56 60</div>
                  <div className="c6c cg30">61 65</div>
                  <div className="c6c cg">66 70</div>
                  <div className="c6c cg">71 75</div>
                  <div className="c6c cy60">76 80</div>
                  <div className="c6c cy30">81 85</div>
                  <div className="c6c cy30">86 90</div>
                  <div className="c6c cy">91 94</div>
                  <div className="c6c cy">95 97</div>
                  <div className="c6c cr">98 99</div>
                  <div className="c6c cr">100</div>
              </div>
              <div className="col7">
                  <div className="chTitles">Excellent</div>
                  <div className="chSymbols">Ex</div>
                  <div className="chNumbers">5</div>
                  <div className="c7c">01</div>
                  <div className="c7c">02 03</div>
                  <div className="c7c">04 06</div>
                  <div className="c7c">07 10</div>
                  <div className="c7c">11 15</div>
                  <div className="c7c">16 20</div>
                  <div className="c7c">21 25</div>
                  <div className="c7c">26 30</div>
                  <div className="c7c cg80">31 35</div>
                  <div className="c7c cg70">36 40</div>
                  <div className="c7c cg60">41 45</div>
                  <div className="c7c cg50">46 50</div>
                  <div className="c7c cg40">51 55</div>
                  <div className="c7c cg30">56 60</div>
                  <div className="c7c cg">61 65</div>
                  <div className="c7c cg">66 70</div>
                  <div className="c7c cy60">71 75</div>
                  <div className="c7c cy30">76 80</div>
                  <div className="c7c cy30">81 85</div>
                  <div className="c7c cy">86 90</div>
                  <div className="c7c cy">91 94</div>
                  <div className="c7c cr60">95 97</div>
                  <div className="c7c cr">98 99</div>
                  <div className="c7c cr">100</div>
              </div>
              <div className="col8">
                  <div className="chTitles">Remarkable</div>
                  <div className="chSymbols">Rm</div>
                  <div className="chNumbers">6</div>
                  <div className="c8c">01</div>
                  <div className="c8c">02 03</div>
                  <div className="c8c">04 06</div>
                  <div className="c8c">07 10</div>
                  <div className="c8c">11 15</div>
                  <div className="c8c">16 20</div>
                  <div className="c8c">21 25</div>
                  <div className="c8c cg80">26 30</div>
                  <div className="c8c cg70">31 35</div>
                  <div className="c8c cg60">36 40</div>
                  <div className="c8c cg50">41 45</div>
                  <div className="c8c cg40">46 50</div>
                  <div className="c8c cg30">51 55</div>
                  <div className="c8c cg">56 60</div>
                  <div className="c8c cg">61 65</div>
                  <div className="c8c cy60">66 70</div>
                  <div className="c8c cy60">71 75</div>
                  <div className="c8c cy30">76 80</div>
                  <div className="c8c cy30">81 85</div>
                  <div className="c8c cy">86 90</div>
                  <div className="c8c cy">91 94</div>
                  <div className="c8c cr60">95 97</div>
                  <div className="c8c cr">98 99</div>
                  <div className="c8c cr">100</div>
              </div>
              <div className="col9"> 
                  <div className="chTitles">Incredible</div>
                  <div className="chSymbols">In</div>
                  <div className="chNumbers">7</div>
                  <div className="c9c">01</div>
                  <div className="c9c">02 03</div>
                  <div className="c9c">04 06</div>
                  <div className="c9c">07 10</div>
                  <div className="c9c">11 15</div>
                  <div className="c9c">16 20</div>
                  <div className="c9c cg80">21 25</div>
                  <div className="c9c cg70">26 30</div>
                  <div className="c9c cg60">31 35</div>
                  <div className="c9c cg50">36 40</div>
                  <div className="c9c cg40">41 45</div>
                  <div className="c9c cg30">46 50</div>
                  <div className="c9c cg">51 55</div>
                  <div className="c9c cg">56 60</div>
                  <div className="c9c cy60">61 65</div>
                  <div className="c9c cy60">66 70</div>
                  <div className="c9c cy30">71 75</div>
                  <div className="c9c cy30">76 80</div>
                  <div className="c9c cy">81 85</div>
                  <div className="c9c cy">86 90</div>
                  <div className="c9c cr70">91 94</div>
                  <div className="c9c cr60">95 97</div>
                  <div className="c9c cr">98 99</div>
                  <div className="c9c cr">100</div>
              </div>
              <div className="col10">
                  <div className="chTitles">Amazing</div>
                  <div className="chSymbols">Am</div>
                  <div className="chNumbers">8</div>
                  <div className="c10c">01</div>
                  <div className="c10c">02 03</div>
                  <div className="c10c">04 06</div>
                  <div className="c10c">07 10</div>
                  <div className="c10c">11 15</div>
                  <div className="c10c cg80">16 20</div>
                  <div className="c10c cg70">21 25</div>
                  <div className="c10c cg60">26 30</div>
                  <div className="c10c cg50">31 35</div>
                  <div className="c10c cg40">36 40</div>
                  <div className="c10c cg30">41 45</div>
                  <div className="c10c cg">46 50</div>
                  <div className="c10c cg">51 55</div>
                  <div className="c10c cy90">56 60</div>
                  <div className="c10c cy60">61 65</div>
                  <div className="c10c cy60">66 70</div>
                  <div className="c10c cy30">71 75</div>
                  <div className="c10c cy30">76 80</div>
                  <div className="c10c cy">81 85</div>
                  <div className="c10c cy">86 90</div>
                  <div className="c10c cr70">91 94</div>
                  <div className="c10c cr60">95 97</div>
                  <div className="c10c cr">98 99</div>
                  <div className="c10c cr">100</div>
              </div> 
              <div className="col11"> 
                  <div className="chTitles">Monstroius</div>
                  <div className="chSymbols">Mn</div>
                  <div className="chNumbers">9</div>
                  <div className="c11c">01</div>
                  <div className="c11c">02 03</div>
                  <div className="c11c">04 06</div>
                  <div className="c11c">07 10</div>
                  <div className="c11c cg80">11 15</div>
                  <div className="c11c cg70">16 20</div>
                  <div className="c11c cg60">21 25</div>
                  <div className="c11c cg50">26 30</div>
                  <div className="c11c cg40">31 35</div>
                  <div className="c11c cg30">36 40</div>
                  <div className="c11c cg">41 45</div>
                  <div className="c11c cg">46 50</div>
                  <div className="c11c cy90">51 55</div>
                  <div className="c11c cy60">56 60</div>
                  <div className="c11c cy60">61 65</div>
                  <div className="c11c cy30">66 70</div>
                  <div className="c11c cy30">71 75</div>
                  <div className="c11c cy">76 80</div>
                  <div className="c11c cy">81 85</div>
                  <div className="c11c cr80">86 90</div>
                  <div className="c11c cr70">91 94</div>
                  <div className="c11c cr60">95 97</div>
                  <div className="c11c cr">98 99</div>
                  <div className="c11c cr">100</div>
              </div>
              <div className="col12"> 
                  <div className="chTitles">Unearthly</div>
                  <div className="chSymbols">Un</div>
                  <div className="chNumbers">10</div>
                  <div className="c12c">01</div>
                  <div className="c12c">02 03</div>
                  <div className="c12c">04 06</div>
                  <div className="c12c cg80">07 10</div>
                  <div className="c12c cg70">11 15</div>
                  <div className="c12c cg60">16 20</div>
                  <div className="c12c cg50">21 25</div>
                  <div className="c12c cg40">26 30</div>
                  <div className="c12c cg30">31 35</div>
                  <div className="c12c cg">36 40</div>
                  <div className="c12c cg">41 45</div>
                  <div className="c12c cycc">46 50</div>
                  <div className="c12c cy90">51 55</div>
                  <div className="c12c cy90">56 60</div>
                  <div className="c12c cy60">61 65</div>
                  <div className="c12c cy60">66 70</div>
                  <div className="c12c cy30">71 75</div>
                  <div className="c12c cy30">76 80</div>
                  <div className="c12c cy">81 85</div>
                  <div className="c12c cr80">86 90</div>
                  <div className="c12c cr70">91 94</div>
                  <div className="c12c cr60">95 97</div>
                  <div className="c12c cr">98 99</div>
                  <div className="c12c cr">100</div>
              </div> 
            </div>  
          </div>
        </div>
    )
}
